### ISSUE TITLE
Interferes with ispell-help

### ISSUE THREAD

**Issue by mmarshall540** [benzanol/echo-bar.el#1]
First, I love this package. I wanted to have Emacs in full-screen, but that hides Gnome's toolbar, which is how I can see what time it is. But I didn't like putting the time in the mode-line, cause that duplicates it in every window, which feels like clutter to me. I also didn't want to put it in the tab-bar cause I only use that rarely. Displaying it in the echo-area is the perfect solution! Encountered a minor problem though...

Description of issue:

When invoking ispell-help, echo-bar-mode interrupts the display of help options after about one second, regardless of `ispell-help-timeout`'s value.

Steps to recreate:

1. Enable `echo-bar-mode`.
2. Confirm that `ispell-help-timeout` is set to the default value of 5 seconds.
3. Locate a misspelled word and place point on the misspelled word.
4. Press `Esc` then `$` (or `M-$`) to invoke `ispell-word`.
5. Per the instructions shown in the echo area, press either `?` or `C-h` to invoke`ispell-help`.
6. Observe that the help information only shows for about a second before disappearing.
7. Disable `echo-bar-mode`
8. Repeat steps 2 through 5.
9. Observe that the help information is now shown for the full 5 seconds.

Curiously, the message shown in step 5 doesn't get interrupted, only the help information does.

I might put together a pull request at some point if I can figure out a solution that isn't too complicated. Thanks again!

**Comment by benzanol** [comment]
Glad you found this package useful.

I was able to reproduce your problem, and this seems to fix it for me.
361f53938809bdba257149eea818f6e9cc34ee2a
It should be fixed with a simple `package-reinstall`.
