### ISSUE TITLE
Prevent echo-bar when no prompt

### ISSUE THREAD

**Issue by jcs090218** [benzanol/echo-bar.el#11]
When something like this: (eval the following)

```elisp
(read-from-minibuffer "")
```

The echo-bar will still display on the screen. It would be great if we could handle this!

**Comment by benzanol** [comment]
Fixed with [1138151](https://github.com/benzanol/echo-bar.el/commit/1138151e55fdfd43126c79caf13169a644b47c00)

**Comment by jcs090218** [comment]
Thank you!
