### ISSUE TITLE
Compatible with the variable `overflow-newline-into-fringe`

### ISSUE THREAD

**Issue by jcs090218** [benzanol/echo-bar.el#13]
#### How to reproduce?

Eval the following.

```elisp
(setq overflow-newline-into-fringe nil)
(setq echo-bar-right-padding 0)
```

![2024-03-01 18 57 42](https://github.com/benzanol/echo-bar.el/assets/8685505/6a19f837-3add-473f-a8f0-0071d2d39c1f)

There is an extra newline at the bottom. Since the variable `overflow-newline-into-fringe` is `nil` now, the `echo-bar` can't render the newline in the right fringe. 

The screenshot is taken with `emacs -q` and on Emacs `29.2`.

#### Other information

My package [sideline](https://github.com/emacs-sideline/sideline) had the same issue, but it's recently been resolved. I hope this bug can be resolved here too.

Here is the link to original issue: https://github.com/emacs-sideline/sideline/issues/18.

**Comment by benzanol** [comment]
I'm not too familiar with `overflow-newline-into-fringe`, but it seems like if its true then the text will necessarily wrap when it is right against the edge. Setting `echo-bar-right-padding` to 1 fixes it for me, is there any reason you don't want to do this?
The only "fix" I can think of is just setting `overflow-newline-into-fringe` to `t` locally in the buffers where the bar is displayed, but I'm not sure if I want to mess with people's variables in this way. But it seems like you have more experience with this variable then me so if there is some other method I would be happy to implement it.

**Comment by jcs090218** [comment]
> I'm not too familiar with overflow-newline-into-fringe, but it seems like if its true then the text will necessarily wrap when it is right against the edge. Setting echo-bar-right-padding to 1 fixes it for me, is there any reason you don't want to do this?

I think the package should handle this. Of course, I can set `echo-bar-right-padding` to 1 or higher, but it would be nice if the package would handle it already.

> The only "fix" I can think of is just setting overflow-newline-into-fringe to t locally in the buffers where the bar is displayed, but I'm not sure if I want to mess with people's variables in this way. But it seems like you have more experience with this variable then me so if there is some other method I would be happy to implement it.

The solution should probably be something like this, see https://github.com/emacs-sideline/sideline/issues/18#issuecomment-1973890606. Just add 1 right padding when this occurs. BTW, I became aware of this variable only because it was brought up in the issue posts of my package.

**Comment by jcs090218** [comment]
Proposing solution in #14. Probably not very elegant. 🤔
